#spring:
#  application:
#    name: ite-sb-api
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASS}

server:
  max-http-request-header-size: 64KB

spring:
  profiles:
    active: dev