package kh.edu.istad.ite.shared.enums;

public enum AdminActionType {

    BUSINESS_ACTIVATED,
    BUSINESS_SUSPENDED,
    BUSINESS_ENABLED,
    BUSINESS_DISABLED,
    BUSINESS_CLOSED,
    BUSINESS_REOPENED,
    BUSINESS_DELETED,

    BUSINESS_CATEGORY_CREATED,
    BUSINESS_CATEGORY_UPDATED,
    BUSINESS_CATEGORY_DELETED,

    UNIT_CREATED,
    UNIT_UPDATED,
    UNIT_DELETED,


    BUSINESS_FEATURE_ENABLED,
    BUSINESS_FEATURE_DISABLED,

    PLATFORM_FEATURE_ENABLED,
    PLATFORM_FEATURE_DISABLED
}
